$:.unshift(File.dirname(__FILE__))

require 'bundler/setup'
require 'zip'
require 'nokogiri'
require 'yaml'
require 'eventmachine'
require 'state_machine'
require 'didv_daemon/conf'
require 'didv_daemon/epub'
require 'didv_daemon/braille'
require 'didv_daemon/ink_text'
require 'didv_daemon/reader'
require 'didv_daemon/writer'
require 'didv_daemon/didv_ux'
require 'didv_daemon/dumb_display'
